### Тестирование поиска книг по названию
GET http://book-library-fedyancev.ru:8085/books?title=Мечтают ли андроиды об электроовцах?

> {%
   client.test('Тестирование поиска книги по названию', function () {
   client.assert(response.status === 200, 'Проверяю код ответа. Фактическое знаение: ' + response.status);
   client.assert(response.contentType.mimeType === "application/json", 'Проверяю application/json. Фактическое знаение: ' + response.contentType.mimeType);
   client.assert(response.body.hasOwnProperty('length') && response.body.length === 1, "В ответе есть один элемент");
   client.assert(response.body[0]['id'] === 10, "id книги не корректен");
   client.assert(response.body[0]['title'] === "Мечтают ли андроиды об электроовцах?", "название книги не корректно");
   client.assert(response.body[0]['year'] === 1966, "год книги не корректен");
   client.assert(response.body[0]['authors'][0]['id'] === 5, "id автора не корректен");
   client.assert(response.body[0]['authors'][0]['name'] === "Филип", "имя не корректен");
   client.assert(response.body[0]['authors'][0]['surname'] === "Дик", "фамилия не корректен");
   client.assert(response.body[0]['authors'][0]['birthday'] === "16.12.1928", "Дата рождения автора не корректен");
   client.assert(response.body[0]['authors'][0]['country'] === "us", "страна не корректен");
 });
 %}

### Тестирование ситуации, когда передали некорректное название книги
GET http://book-library-fedyancev.ru:8085/books?title[]=Мечтают ли андроиды об электроовцах?

> {%
     client.test("Тестирование ситуации, когда передали некорректное имя автора для поиска книги", function () {
            client.assert(response.status === 500, 'Проверяю код ответа. Фактическое знаение: ' + response.status);
            client.assert(response.contentType.mimeType === "application/json", 'Проверяю application/json. Фактическое знаение: ' + response.contentType.mimeType);
            client.assert(response.body['status'] === "fail", "Некорректный статус");
            client.assert(response.body['message'] === "incorrect book title", "Некорректное сообщение");
     })
 %}

### Тестирование ситуации, когда передали некорректное название книги
GET http://book-library-fedyancev.ru:8085/books?author_surname[]=Дик

> {%
     client.test("Тестирование ситуации, когда передали некорректное имя автора для поиска книги", function () {
            client.assert(response.status === 500, 'Проверяю код ответа. Фактическое знаение: ' + response.status);
            client.assert(response.contentType.mimeType === "application/json", 'Проверяю application/json. Фактическое знаение: ' + response.contentType.mimeType);
            client.assert(response.body['status'] === "fail", "Некорректный статус");
            client.assert(response.body['message'] === "incorrect author surname", "Некорректное сообщение");
     })
 %}


### Тестирование поиска книг по фамилии автора
GET http://book-library-fedyancev.ru:8085/books?author_surname=Дик

> {%
 client.test('Тестирование поиска книг по фамилии автора', function () {
   client.assert(response.status === 200, 'Проверяю код ответа. Фактическое знаение: ' + response.status);
   client.assert(response.contentType.mimeType === "application/json", 'Проверяю application/json. Фактическое знаение: ' + response.contentType.mimeType);
   client.assert(response.body.hasOwnProperty('length') && response.body.length === 1, "В ответе есть один элемент");
   client.assert(response.body[0]['id'] === 10, "id книги не корректен");
   client.assert(response.body[0]['title'] === "Мечтают ли андроиды об электроовцах?", "название книги не корректно");
   client.assert(response.body[0]['year'] === 1966, "год книги не корректен");
   client.assert(response.body[0]['authors'][0]['id'] === 5, "id автора не корректен");
   client.assert(response.body[0]['authors'][0]['name'] === "Филип", "имя не корректен");
   client.assert(response.body[0]['authors'][0]['surname'] === "Дик", "фамилия не корректен");
   client.assert(response.body[0]['authors'][0]['birthday'] === "16.12.1928", "Дата рождения автора не корректен");
   client.assert(response.body[0]['authors'][0]['country'] === "us", "страна не корректен");
   })
%}

### Тестирование поиска авторов по фамилии
GET http://book-library-fedyancev.ru:8085/authors?surname=Паланик

> {%
  client.test("Тестирование поиска авторов по фамилии", function () {
      client.assert(response.status === 200, 'Проверяю код ответа. Фактическое знаение: ' + response.status);
      client.assert(response.contentType.mimeType === "application/json", 'Проверяю application/json. Фактическое знаение: ' + response.contentType.mimeType);
      client.assert(response.body.hasOwnProperty('length') && response.body.length === 1, "В ответе есть один элемент");
      client.assert(response.body[0]['id'] === 1, "id автора не корректен");
      client.assert(response.body[0]['name'] === "Чак", "имя не корректен");
      client.assert(response.body[0]['surname'] === "Паланик", "фамилия не корректен");
      client.assert(response.body[0]['birthday'] === "21.02.1962", "Дата рождения автора не корректен");
      client.assert(response.body[0]['country'] === "us", "страна не корректен");
  })
%}


### Тестирование неподдерживаемого приложения url
GET http://book-library-fedyancev.ru:8085/hhh?param=ru

> {%
     client.test("Неподдерживаемый запрос", function () {
            client.assert(response.status === 404, 'Проверяю код ответа. Фактическое знаение: ' + response.status);
            client.assert(response.contentType.mimeType === "application/json", 'Проверяю application/json. Фактическое знаение: ' + response.contentType.mimeType);
            client.assert(response.body['status'] === "fail", "Некорректный статус");
            client.assert(response.body['message'] === "unsupported request", "Некорректное сообщение");
     })
 %}

### Тестирование запроса без path
GET http://book-library-fedyancev.ru:8085/?param=ru

> {%
     client.test("Неподдерживаемый запрос", function () {
            client.assert(response.status === 404, 'Проверяю код ответа. Фактическое знаение: ' + response.status);
            client.assert(response.contentType.mimeType === "application/json", 'Проверяю application/json. Фактическое знаение: ' + response.contentType.mimeType);
            client.assert(response.body['status'] === "fail", "Некорректный статус");
            client.assert(response.body['message'] === "unsupported request", "Некорректное сообщение");
     })
 %}

### Тестирование ситуации, когда передали некорректное название книги
GET http://book-library-fedyancev.ru:8085/authors?surname[]=Дик

> {%
     client.test("Тестирование ситуации, когда передали некорректное имя автора для поиска книги", function () {
            client.assert(response.status === 500, 'Проверяю код ответа. Фактическое знаение: ' + response.status);
            client.assert(response.contentType.mimeType === "application/json", 'Проверяю application/json. Фактическое знаение: ' + response.contentType.mimeType);
            client.assert(response.body['status'] === "fail", "Некорректный статус");
            client.assert(response.body['message'] === "incorrect author surname", "Некорректное сообщение");
     })
 %}

### Тестирование поиска журнала по названию
GET http://book-library-fedyancev.ru:8085/books?title=Логос

> {%
   client.test('Тестирование поиска журнала по названию', function () {
   client.assert(response.status === 200, 'Проверяю код ответа. Фактическое знаение: ' + response.status);
   client.assert(response.contentType.mimeType === "application/json", 'Проверяю application/json. Фактическое знаение: ' + response.contentType.mimeType);
   client.assert(response.body.hasOwnProperty('length') && response.body.length === 1, "В ответе есть один элемент");
   client.assert(response.body[0]['id'] === 17, "id журнала не корректен");
   client.assert(response.body[0]['title'] === "Логос", "название журнала не корректно");
   client.assert(response.body[0]['year'] === 2020, "год журнала не корректен");
   client.assert(response.body[0]['number'] === 1, "номер не корректен");
 });
 %}


### Тестирование получения печатного изданияя по ID
GET http://book-library-fedyancev.ru:8085/books/17

> {%
   client.test('Тестирование получения печатного изданияя по ID', function () {
   client.assert(response.status === 200, 'Проверяю код ответа. Фактическое знаение: ' + response.status);
   client.assert(response.contentType.mimeType === "application/json", 'Проверяю application/json. Фактическое знаение: ' + response.contentType.mimeType);
   client.assert(response.body['id'] === 17, "id журнала не корректен");
   client.assert(response.body['title'] === "Логос", "название журнала не корректно");
   client.assert(response.body['year'] === 2020, "год журнала не корректен");
   client.assert(response.body['number'] === 1, "номер не корректен");
 });
 %}



### Тестирование ситуации когда указан не существующий id
GET http://book-library-fedyancev.ru:8085/books/0

> {%
     client.test("Тестирование ситуации когда указан не существующий id", function () {
            client.assert(response.status === 404, 'Проверяю код ответа. Фактическое знаение: ' + response.status);
            client.assert(response.contentType.mimeType === "application/json", 'Проверяю application/json. Фактическое знаение: ' + response.contentType.mimeType);
            client.assert(response.body['status'] === "fail", "Некорректный статус");
            client.assert(response.body['message'] === "entity not found", "Некорректное сообщение");
     })
 %}

### Тестирование получения автора по ID
GET http://book-library-fedyancev.ru:8085/authors/1

> {%
  client.test("### Тестирование получения автора по ID", function () {
      client.assert(response.status === 200, 'Проверяю код ответа. Фактическое знаение: ' + response.status);
      client.assert(response.contentType.mimeType === "application/json", 'Проверяю application/json. Фактическое знаение: ' + response.contentType.mimeType);
      client.assert(response.body['id'] === 1, "id автора не корректен");
      client.assert(response.body['name'] === "Чак", "имя не корректен");
      client.assert(response.body['surname'] === "Паланик", "фамилия не корректен");
      client.assert(response.body['birthday'] === "21.02.1962", "Дата рождения автора не корректен");
      client.assert(response.body['country'] === "us", "страна не корректен");
  })
%}

### Тестирование ситуации когда указан не существующий id автора
GET http://localhost:8085/authors/0

> {%
     client.test("Тестирование ситуации когда указан не существующий id автора", function () {
            client.assert(response.status === 404, 'Проверяю код ответа. Фактическое знаение: ' + response.status);
            client.assert(response.contentType.mimeType === "application/json", 'Проверяю application/json. Фактическое знаение: ' + response.contentType.mimeType);
            client.assert(response.body['status'] === "fail", "Некорректный статус");
            client.assert(response.body['message'] === "entity not found", "Некорректное сообщение");
     })
 %}


### Тестирование получения автора по ID
GET http://book-library-fedyancev.ru:8085/authors

### Отправка книг в архив
PUT http://book-library-fedyancev.ru:8085/books/6/moveToArchive

> {%
   client.test('Отправка книг в архив', function () {
   client.assert(response.status === 200, 'Проверяю код ответа. Фактическое знаение: ' + response.status);
   client.assert(response.contentType.mimeType === "application/json", 'Проверяю application/json. Фактическое знаение: ' + response.contentType.mimeType);
   client.assert(response.body['id'] === 6, "id журнала не корректен");
   client.assert(response.body['status'] === "archive", "статус книги не корректен");
   client.assert(response.body['title_for_printing'] === 'Glamorama .Эллис Брет 1998', "название книги не корректно");
 });
 %}

### Регистрация новой книги
POST http://book-library-fedyancev.ru:8085/books/register
Content-Type: application/json

{
  "title" : "Текстовой документ",
  "year": 2021,
  "author_id_list" : [1,2,3]
}

> {%
   client.test('Тестирование регистрации новой книги', function () {
   client.assert(response.status === 201, 'Проверяю код ответа. Фактическое знаение: ' + response.status);
   client.assert(response.contentType.mimeType === "application/json", 'Проверяю application/json. Фактическое знаение: ' + response.contentType.mimeType);
   client.assert(response.body.hasOwnProperty('id'), "Отсутствует id книги");
   client.assert(response.body['status'] === "inStock", "статус книги не корректен");
   client.assert(response.body['title_for_printing'] === 'Текстовой документ .Кормильцев Илья, Паланик Чак, Эллис Брет 2021', "название книги не корректно");
 });
 %}


### Регистрация нового журнала
POST http://book-library-fedyancev.ru:8085/magazines/register
Content-Type: application/json

{
  "title" : "Новый журнал",
  "year": 2021,
  "author_id_list" : [1,2,3],
  "number": 10
}

> {%
   client.test('Тестирование регистрации нового журнала', function () {
   client.assert(response.status === 201, 'Проверяю код ответа. Фактическое знаение: ' + response.status);
   client.assert(response.contentType.mimeType === "application/json", 'Проверяю application/json. Фактическое знаение: ' + response.contentType.mimeType);
   client.assert(response.body.hasOwnProperty('id'), "Отсутствует id журнала");
   client.assert(response.body['status'] === "inStock", "статус журнала не корректен");
   client.assert(response.body['title_for_printing'] === 'Новый журнал. 2021. Номер: 10.', "название книги не корректно");
 });
 %}


### Отладка формы логина
POST http://book-library-fedyancev.ru:8085/login?redirect=http://book-library-fedyancev.ru:8083/text-document/administration
Content-Type: text/html


### логина
POST http://book-library-fedyancev.ru:8085/text-document/administration